name: ci_backend

on:
  pull_request:
    branches:
      - dev
      - stg
      - main
    types:
      - opened    
      - reopened
      - synchronize


env: 
  ECS_TASK_DEFINITION: taskdefinition.json
  ECR_REPOSITORY: myrep
  CONTAINER_NAME: backend-1
  ECS_SERVICE: backend-1-service

jobs:
  ci_backend:
    environment: production
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout  
      uses: actions/checkout@v4
      with:
        submodules: recursive



# ----------------------------------------

# Set up run time and build
# https://docs.github.com/en/actions/automating-builds-and-tests


    - name: test and upload test result
      run: |
        
        mkdir results
        touch results/sample.txt
        date >> results/sample.txt
      # continue-on-error: true

    - name: Upload Unit Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Unit Test Results
        path: results/*.txt
        # retention-days: 5

