name: Terraform Plan

# on:
#     workflow_call:
on:
  pull_request:
    branches:
      - dev
      - stg
      - prod
    types:
      - opened
      # - closed

env: 
  # ENVIRONMENT: environments/dev
  TERRAFORM_VERSION: 1.7.3
  TFLINT_VERSION: v0.50.3




jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout  
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{env.TERRAFORM_VERSION}}
    
    - name: Init & Fmt terraform
      run: |
        cd environments/${{ github.base_ref }}
        pwd
        terraform init
        terraform fmt -check -recursive

    - uses: terraform-linters/setup-tflint@v4
      name: Setup tflint
      with:
        tflint_version: ${{env.TFLINT_VERSION}}

    - name: Init & Run TFLint
      run: |
        tflint --init
        tflint -f compact

    - name: Terraform Plan
      id: plan
      run: |
        cd environments/${{ github.base_ref }}
        pwd
        terraform plan
      continue-on-error: true

    - name: Comment PR
      uses: actions/github-script@v3
      with:
        script: |
          const output = `#### Terraform Plan 📖\`${{ steps.plan.outputs.stdout }}\``;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## Terraform checks in directory '${{ matrix.directory }}'\n` + output
          })