name: tfdeploy

on:
  push:

env: 
  TERRAFORM_VERSION: 1.7.1
  TFLINT_VERSION: v0.39.2




jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout  
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: $TERRAFORM_VERSION
    
    - name: Init & Fmt terraform
      run: |
        terraform init
        terraform fmt -check -recursive

    - uses: terraform-linters/setup-tflint@v4
      name: Setup tflint
      with:
        tflint_version: $TFLINT_VERSION

    - name: Init & Run TFLint
      run: |
        tflint --init
        tflint -f compact
