name: Test Submodule

on:
    push:
# on:
#   pull_request:
#     branches:
#       - dev
#     types:
#       - opened    
#       - closed

env: 
#  ENVIRONMENT: environments/dev
  TERRAFORM_VERSION: 1.7.3
  TFLINT_VERSION: v0.50.3




jobs:
  TEST:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout  
      uses: actions/checkout@v4

    - name: Echo
      run: echo "cat sub/subfile"